### ISSUE TITLE
Guided Mode: Variability screen gets out of sync if response variables removed

### ISSUE THREAD

**Issue by SampleSizeShop** [SampleSizeShop/GlimmpseWWW#52]
**A user reported the following error when calculating sample size:**

Power Results

Bad Request

Missing covariance information for factor: Months

You can get technical details here.
Please continue your visit at our home page.

**User email:**

I am sorry to bother you again. 
Something went wrong when typing the response variable, and therefore I wasn’t able to select hypothesis, means and variability. 

After I filled in the response variable, I could also fill in the hypothesis, means and variability. 

The button ‘calculate’ became green. I pressed it, but unfortunately I’ve got the following error:  
    
I don’t understand what went wrong, since I filled in everything. 
If you have time, I would really appreciate it if you can help me. In the attachment you can find the data that I’ve filled in. 

**Suspected issue:**
I suspect the user entered most of the study design including hypothesis/means/etc and then went back to the response variables screen and removed the response.  This likely removed the repeated measures covariance information.  If they did not return to the repeated measures screen after re-adding the response variable, it is possible the repeated measures covariance block is never recreated.

Below is the user's original json
{"uuid":[],"name":null,"gaussianCovariate":true,"solutionTypeEnum":"SAMPLE_SIZE","participantLabel":null,"viewTypeEnum":"GUIDED_MODE","confidenceIntervalDescriptions":null,"powerCurveDescriptions":null,"alphaList":[{"idx":0,"alphaValue":0.05},{"idx":1,"alphaValue":0.01},{"idx":2,"alphaValue":1}],"betaScaleList":[{"idx":0,"value":1},{"idx":1,"value":0.5},{"idx":2,"value":2}],"sigmaScaleList":[{"idx":0,"value":1},{"idx":1,"value":0.5},{"idx":2,"value":2}],"relativeGroupSizeList":[{"idx":0,"value":1},{"idx":0,"value":1},{"idx":0,"value":1},{"idx":0,"value":1}],"sampleSizeList":[],"statisticalTestList":[{"idx":"0","type":"HLT"}],"powerMethodList":[{"idx":0,"powerMethodEnum":"UNCONDITIONAL"}],"quantileList":[],"nominalPowerList":[{"idx":0,"value":0.8},{"idx":1,"value":0.9}],"responseList":[{"idx":0,"name":"400-meter walk speed"}],"betweenParticipantFactorList":[{"idx":0,"predictorName":"Health status","categoryList":[{"idx":0,"category":"Healthy"},{"idx":0,"category":"Frail"}]},{"idx":1,"predictorName":"Treatment","categoryList":[{"idx":0,"category":"Placebo"},{"idx":0,"category":"Carnitine"}]}],"repeatedMeasuresTree":[{"idx":0,"node":0,"parent":0,"repeatedMeasuresDimensionType":"NUMERICAL","numberOfMeasurements":3,"spacingList":[{"idx":1,"value":1},{"idx":2,"value":2},{"idx":3,"value":3}],"dimension":"Months"}],"clusteringTree":[],"hypothesis":[{"idx":1,"type":"INTERACTION","betweenParticipantFactorMapList":[{"type":"NONE","betweenParticipantFactor":{"idx":0,"predictorName":"Health status","categoryList":[{"idx":0,"category":"Healthy"},{"idx":0,"category":"Frail"}]}},{"type":"NONE","betweenParticipantFactor":{"idx":1,"predictorName":"Treatment","categoryList":[{"idx":0,"category":"Placebo"},{"idx":0,"category":"Carnitine"}]}}],"repeatedMeasuresMapTree":[{"type":"NONE","repeatedMeasuresNode":{"idx":0,"node":0,"parent":0,"repeatedMeasuresDimensionType":"NUMERICAL","numberOfMeasurements":3,"spacingList":[{"idx":1,"value":1},{"idx":2,"value":2},{"idx":3,"value":3}],"dimension":"Months"}}]}],"covariance":[{"idx":0,"type":"UNSTRUCTURED_CORRELATION","name":"__RESPONSE_COVARIANCE__","standardDeviationList":[{"idx":0,"value":0.2}],"rho":-2,"delta":-1,"rows":1,"columns":1,"blob":{"data":[[1]]}}],"matrixSet":[{"idx":0,"rows":1,"columns":1,"name":"sigmaGaussianRandom","data":{"data":[[8]]}},{"idx":0,"name":"beta","rows":4,"columns":3,"data":{"data":[[0.86,0.84,0.82],[0.86,0.87,0.85],[1.34,1.32,1.3],[1.34,1.34,1.34]]}},{"idx":0,"name":"betaRandom","rows":1,"columns":3,"data":{"data":[[1,1,1]]}},{"idx":0,"name":"sigmaOutcomeGaussianRandom","rows":3,"columns":1,"data":{"data":[[0.5],[0.4],[0.3]]}}]}

**Comment by sstodghill** [comment]
Moved to https://samplesizeshop.atlassian.net/browse/SSS-17
