### ISSUE TITLE
MathJax Chrome errors

### ISSUE THREAD

**Issue by sstodghill** [SampleSizeShop/GlimmpseWWW#53]
Study below renders MathJax errors after successful.  Matrices render correctly on OS X Yosemite Safari, Firefox and Chrome.  Steps to reproduce:
- OS: Windows
- Browser: Chrome 39.0
- save JSON below to study.json
- Upload to GLIMMPSE  (http://glimmpse.samplesizeshop.org/#/)
- Calculate
- Matrices
- note MathJax errors

``` json
{"uuid":[],"name":null,"gaussianCovariate":false,"solutionTypeEnum":"POWER","participantLabel":null,"viewTypeEnum":"GUIDED_MODE","confidenceIntervalDescriptions":null,"powerCurveDescriptions":{"idx":0,"legend":true,"width":300,"height":300,"title":null,"horizontalAxisLabelEnum":"TOTAL_SAMPLE_SIZE","dataSeriesList":[{"idx":0,"label":"Series 1","confidenceLimits":false,"statisticalTestTypeEnum":"HLT","betaScale":1,"sigmaScale":1,"typeIError":0.0083}]},"alphaList":[{"idx":0,"alphaValue":0.0083}],"betaScaleList":[{"idx":0,"value":1}],"sigmaScaleList":[{"idx":0,"value":1}],"relativeGroupSizeList":[{"idx":0,"value":1},{"idx":0,"value":1},{"idx":0,"value":1}],"sampleSizeList":[{"idx":0,"value":10},{"idx":1,"value":11},{"idx":2,"value":12},{"idx":3,"value":13},{"idx":4,"value":14},{"idx":5,"value":15},{"idx":6,"value":16},{"idx":7,"value":17},{"idx":8,"value":18},{"idx":9,"value":19},{"idx":10,"value":20},{"idx":11,"value":21},{"idx":12,"value":22},{"idx":13,"value":23},{"idx":14,"value":24},{"idx":15,"value":25},{"idx":16,"value":26},{"idx":17,"value":27},{"idx":18,"value":28},{"idx":19,"value":29},{"idx":20,"value":30},{"idx":21,"value":31},{"idx":22,"value":32},{"idx":23,"value":33},{"idx":24,"value":34},{"idx":25,"value":35},{"idx":26,"value":36},{"idx":27,"value":37},{"idx":28,"value":38},{"idx":29,"value":39},{"idx":30,"value":40},{"idx":31,"value":41},{"idx":32,"value":42},{"idx":33,"value":43},{"idx":34,"value":44},{"idx":35,"value":45},{"idx":36,"value":46},{"idx":37,"value":47},{"idx":38,"value":48},{"idx":39,"value":49},{"idx":40,"value":50}],"statisticalTestList":[{"idx":"0","type":"HLT"}],"powerMethodList":[],"quantileList":[],"nominalPowerList":[],"responseList":[{"idx":0,"name":"co"}],"betweenParticipantFactorList":[{"idx":0,"predictorName":"group","categoryList":[{"idx":0,"category":"eg"},{"idx":0,"category":"sc"},{"idx":0,"category":"ivf"}]}],"repeatedMeasuresTree":[{"idx":0,"node":0,"parent":0,"repeatedMeasuresDimensionType":"NUMERICAL","numberOfMeasurements":3,"spacingList":[{"idx":1,"value":5.5},{"idx":2,"value":8},{"idx":3,"value":14}],"dimension":"weeks"}],"clusteringTree":[],"hypothesis":[{"idx":1,"type":"INTERACTION","betweenParticipantFactorMapList":[{"type":"NONE","betweenParticipantFactor":{"idx":0,"predictorName":"group","categoryList":[{"idx":0,"category":"eg"},{"idx":0,"category":"sc"},{"idx":0,"category":"ivf"}]}}],"repeatedMeasuresMapTree":[{"type":"ALL_POLYNOMIAL","repeatedMeasuresNode":{"idx":0,"node":0,"parent":0,"repeatedMeasuresDimensionType":"NUMERICAL","numberOfMeasurements":3,"spacingList":[{"idx":1,"value":5.5},{"idx":2,"value":8},{"idx":3,"value":14}],"dimension":"weeks"}}]}],"covariance":[{"idx":0,"type":"LEAR_CORRELATION","name":"weeks","standardDeviationList":[{"idx":0,"value":1},{"idx":0,"value":1},{"idx":0,"value":1}],"rho":0.5,"delta":1,"rows":3,"columns":3,"blob":{"data":[[1,0.1767766952966369,0.08838834764831845],[0.1767766952966369,1,0.11798428908521168],[0.08838834764831845,0.11798428908521168,1]]}},{"idx":0,"type":"UNSTRUCTURED_CORRELATION","name":"__RESPONSE_COVARIANCE__","standardDeviationList":[{"idx":0,"value":0.114}],"rho":-2,"delta":-1,"rows":1,"columns":1,"blob":{"data":[[1]]}}],"matrixSet":[{"idx":0,"name":"beta","rows":3,"columns":3,"data":{"data":[[1.72,1.77,1.87],[1.76,1.82,1.95],[1.79,1.86,2.01]]}}]}
```

**Comment by SampleSizeShop** [comment]
Sucks.
Can you fix?


Deb Glueck, Ph.D.
Associate Professor
Department of Biostatistics
Colorado School of Public Health
University of Colorado Denver
Historic Building 500
Room W3125
13001 E. 17th Place<x-apple-data-detectors://0>
Mail Stop C245<x-apple-data-detectors://0>
Aurora, CO 80045<x-apple-data-detectors://0>

Phone:  303-724-4358<tel:303-724-4358>
Fax:      303-724-4491<tel:303-724-4491>
E-mail: Deborah.Glueck@ucdenver.edu<mailto:Deborah.Glueck@ucdenver.edu>


On Jan 18, 2015, at 2:37 PM, "Scott Stodghill" <notifications@github.com<mailto:notifications@github.com>> wrote:


Study below renders MathJax errors after successful. Matrices render correctly on OS X Yosemite Safari, Firefox and Chrome. Steps to reproduce:

  *   OS: Windows
  *   Browser: Chrome 39.0
  *   save JSON below to study.json
  *   Upload to GLIMMPSE (http://glimmpse.samplesizeshop.org/#/)
  *   Calculate
  *   Matrices
  *   note MathJax errors

{"uuid":[],"name":null,"gaussianCovariate":false,"solutionTypeEnum":"POWER","participantLabel":null,"viewTypeEnum":"GUIDED_MODE","confidenceIntervalDescriptions":null,"powerCurveDescriptions":{"idx":0,"legend":true,"width":300,"height":300,"title":null,"horizontalAxisLabelEnum":"TOTAL_SAMPLE_SIZE","dataSeriesList":[{"idx":0,"label":"Series 1","confidenceLimits":false,"statisticalTestTypeEnum":"HLT","betaScale":1,"sigmaScale":1,"typeIError":0.0083}]},"alphaList":[{"idx":0,"alphaValue":0.0083}],"betaScaleList":[{"idx":0,"value":1}],"sigmaScaleList":[{"idx":0,"value":1}],"relativeGroupSizeList":[{"idx":0,"value":1},{"idx":0,"value":1},{"idx":0,"value":1}],"sampleSizeList":[{"idx":0,"value":10},{"idx":1,"value":11},{"idx":2,"value":12},{"idx":3,"value":13},{"idx":4,"value":14},{"idx":5,"value":15},{"idx":6,"value":16},{"idx":7,"value":17},{"idx":8,"value":18},{"idx":9,"value":19},{"idx":10,"value":20},{"idx":11,"value":21},{"idx":12,"val
 ue":22},
 {"idx":13,"value":23},{"idx":14,"value":24},{"idx":15,"value":25},{"idx":16,"value":26},{"idx":17,"value":27},{"idx":18,"value":28},{"idx":19,"value":29},{"idx":20,"value":30},{"idx":21,"value":31},{"idx":22,"value":32},{"idx":23,"value":33},{"idx":24,"value":34},{"idx":25,"value":35},{"idx":26,"value":36},{"idx":27,"value":37},{"idx":28,"value":38},{"idx":29,"value":39},{"idx":30,"value":40},{"idx":31,"value":41},{"idx":32,"value":42},{"idx":33,"value":43},{"idx":34,"value":44},{"idx":35,"value":45},{"idx":36,"value":46},{"idx":37,"value":47},{"idx":38,"value":48},{"idx":39,"value":49},{"idx":40,"value":50}],"statisticalTestList":[{"idx":"0","type":"HLT"}],"powerMethodList":[],"quantileList":[],"nominalPowerList":[],"responseList":[{"idx":0,"name":"co"}],"betweenParticipantFactorList":[{"idx":0,"predictorName":"group","categoryList":[{"idx":0,"category":"eg"},{"idx":0,"category":"sc"},{"idx":0,"category":"ivf"}]}],"repeatedMeasuresTree":[{"idx":0,"node":0,"parent":0,"repeat
 edMeasur
 esDimensionType":"NUMERICAL","numberOfMeasurements":3,"spacingList":[{"idx":1,"value":5.5},{"idx":2,"value":8},{"idx":3,"value":14}],"dimension":"weeks"}],"clusteringTree":[],"hypothesis":[{"idx":1,"type":"INTERACTION","betweenParticipantFactorMapList":[{"type":"NONE","betweenParticipantFactor":{"idx":0,"predictorName":"group","categoryList":[{"idx":0,"category":"eg"},{"idx":0,"category":"sc"},{"idx":0,"category":"ivf"}]}}],"repeatedMeasuresMapTree":[{"type":"ALL_POLYNOMIAL","repeatedMeasuresNode":{"idx":0,"node":0,"parent":0,"repeatedMeasuresDimensionType":"NUMERICAL","numberOfMeasurements":3,"spacingList":[{"idx":1,"value":5.5},{"idx":2,"value":8},{"idx":3,"value":14}],"dimension":"weeks"}}]}],"covariance":[{"idx":0,"type":"LEAR_CORRELATION","name":"weeks","standardDeviationList":[{"idx":0,"value":1},{"idx":0,"value":1},{"idx":0,"value":1}],"rho":0.5,"delta":1,"rows":3,"columns":3,"blob":{"data":[[1,0.1767766952966369,0.08838834764831845],[0.1767766952966369,1,0.1179842890
 8521168]
 ,[0.08838834764831845,0.11798428908521168,1]]}},{"idx":0,"type":"UNSTRUCTURED_CORRELATION","name":"__RESPONSE_COVARIANCE__","standardDeviationList":[{"idx":0,"value":0.114}],"rho":-2,"delta":-1,"rows":1,"columns":1,"blob":{"data":[[1]]}}],"matrixSet":[{"idx":0,"name":"beta","rows":3,"columns":3,"data":{"data":[[1.72,1.77,1.87],[1.76,1.82,1.95],[1.79,1.86,2.01]]}}]}

-

**Comment by SampleSizeShop** [comment]
Moved MathJax to be loaded via CDN so it loads quicker.  Have not had report of this problem since then.
